# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'CS373 Spring 2018: Davis Robertson'
tagline:          'SWE Blog'
description:      'I&#39;m <a href="http://daviskr.com/">Davis Robertson</a>, and this is my blog for SWE CS373.'
url:              http://daviskr.com/swe-blog/
baseurl:          /swe-blog 

author:
  name:           'Davis Robertson'
  url:            http://daviskr.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/epicdavi/blog/
  gravatar:       "https://avatars3.githubusercontent.com/u/3261707?s=300"

gaid:             UA-50584050-1
